package.json
protos/google/pubsub/v1/pubsub.proto
samples/subscriptions.js
samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js
src/connection-pool.js
src/iam.js
src/index.js
src/publisher.js
src/snapshot.js
src/subscription.js
src/topic.js
src/v1/index.js
src/v1/publisher_client.js
src/v1/subscriber_client.js
test/connection-pool.js
test/iam.js
test/index.js
test/publisher.js
test/snapshot.js
test/subscription.js
test/topic.js

This is a new generated code for pubsub. We need to make sure it works with the existing manual code under src/.

New generated code

---

system-test/pubsub.js

refactor before hook to wait for topics

---

system-test/pubsub.js

Relates to #5
We've been seeing consistent failures of `getTopics()` system-tests on CircleCI. After digging in, I believe the issue is that we are are half-initializing several Topic objects and comparing the names of said objects against the names returned from the API.
Why is that an issue? Well unless a project id environment variable is set, we use a placeholder `{{projectId}}` that could cause the comparison to fail, which would explain the failing tests. This will instead compare the short names which should be unique ids.

filter topics by short names

---

src/iam.js
src/index.js
src/publisher.js
src/snapshot.js
src/subscription.js
src/topic.js
test/iam.js
test/index.js
test/publisher.js
test/snapshot.js
test/subscription.js
test/topic.js

Support Promise override.

---

package.json

I don't think this is going to be a breaking change ;-)
- [ x ] Tests and linter pass
- [ x ] Code coverage does not decrease (if any source code was changed)
- [ x ] Appropriate docs were updated (if necessary)

Full name update

---

package.json

GoogleCloudPlatform/google-cloud-node#2784
grpc/grpc-node#130
googleapis/nodejs-datastore#35
Fixes #31

Downgrade gRPC to ~1.7

---

src/index.js
test/index.js

Normalize options argument for all instantiations.

---

src/index.js

docs: remove stale example

---

samples/subscriptions.js
src/subscription.js

Use autoCreate in flow control sample.

---

src/subscription.js
test/subscription.js

Relates to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2810

change maxMessages default to 100

---

src/publisher.js
test/publisher.js

feat(publisher): accept gax options

---

src/connection-pool.js
src/subscription.js
test/connection-pool.js
test/subscription.js

I've noticed duplicate errors being emitted, these changes will cut down on the number of errors we emit.

refactor error handling

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

- (#22, #110) A Publisher object now supports configuration of API request parameters. For example, this allows you to specify the number of retries for a request.
- (#109) Muffle extraneous `streamingPull` errors.
- (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2810, #107) Change Subscription `maxMessages` default value from `Infinity` to `100` to prevent intense memory usage.

chore: prep release for 0.18.0

---

samples/system-test/topics.test.js
samples/topics.js

Added sample for publishing messages with custom attributes

---

package-lock.json
package.json
samples/package-lock.json

fix(package): update google-auto-auth to version 0.10.1

---

samples/quickstart.js
samples/subscriptions.js
samples/topics.js

PubSub: Updates region tags to standard and deletes unused tags

---

samples/package.json
samples/system-test/subscriptions.test.js
system-test/pubsub.js
test/connection-pool.js
test/iam.js
test/index.js
test/publisher.js
test/snapshot.js
test/subscriber.js
test/subscription.js
test/topic.js

chore: fix the eslint errors

---

samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js

fix: System tests were using get() incorrectly.

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.21.1

---

samples/subscriptions.js

The last PR on this file forgot to take out the outdated comments.

docs: remove outdated comments

---

test/index.ts

Fixes #311 partially for test/index.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for test/index.ts

---

test/iam.ts

Fixes #311 partially for test/iam.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for test/iam.ts

---

test/connection-pool.ts

Fixes #311 partially for test/connection-pool.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for test/connection-pool.ts

---

src/util.ts

Fixes #311 partially for src/util.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for src/util.ts

---

src/topic.ts

Fixes #311 partially for src/topic.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for src/topic.ts

---

src/subscription.ts

Fixes #311 partially for src/subscription.js (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for src/subscription.ts

---

test/snapshot.ts

Fixes #311 partially for test/snapshot.ts (it's a good idea to open an issue first for discussion)

refactor(ts): Added ts style fix for test/snapshot.ts

---

test/subscriber.ts

Fixes #311 partially for test/subscriber.ts (it's a good idea to open an issue first for discussion)

refactor(ts): Added ts style fix for test/subscriber.ts

---

test/subscription.ts

Fixes #311 partially for test/subscription.ts (it's a good idea to open an issue first for discussion)

refactor(ts): Added ts style fix for test/subscription.ts

---

test/topic.ts

Fixes #311 partially for test/topic.ts (it's a good idea to open an issue first for discussion)

refactor(ts): Added ts style fix for test/topic.ts

---

system-test/pubsub.ts

Fixes #311 partially for system-test/pubsub.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for system-test/pubsub.ts

---

CHANGELOG.md
package.json
samples/package.json

feat: release @google-cloud/pubsub v0.22.0

---

src/publisher.ts

docs: Add documentation about defaults for publisher

---

src/subscription.ts

docs: Update documentation for Subscription

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.22.1

---

src/index.ts
test/index.ts

fix(publisher): unbound max send message size

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.24.1

---

test/topic.ts

refactor(typescript) changes for #313 (it's a good idea to open an issue first for discussion)

refactor(typescript): noImplicityAny for Topic test file

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.26.0

---

test/lease-manager.ts

refactor(typescript):noImplicitAny for lease-manager test file

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.27.1

---

src/subscription.ts
test/histogram.ts
test/subscription.ts

Fixes #313 (it's a good idea to open an issue first for discussion)
All files in test, src and system-test folder is done!

refactor(typescript): noImplicitAny for Subscription test file

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.28.1

---

src/message-stream.ts
test/message-stream.ts

feat(subscription): accept pull deadline option

---

samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js

checking to see if the problem with tests was related to invalid regexes being created

chore: switch to include from match

---

package.json
samples/package.json
samples/system-test/quickstart.test.js
samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js

automerge merged the last PR before my changes were pushed.

fix: relax strictEqual to match RegExp

---

test/snapshot.ts

test: fix snapshot fixture creation

---

src/message-stream.ts
src/pull-retry.ts
test/message-stream.ts
test/pull-retry.ts

This was going to fix a couple things, but it has morphed into something else and won't fix anything now. 🤷‍♂

refactor(subscriber): message stream retry logic

---

CHANGELOG.md

docs: fix npm link for @google-cloud/pubsub

---

samples/subscriptions.js
samples/system-test/topics.test.js
src/message-queues.ts
synth.py

fix: update regex to target correct comment

---

package.json

fix(deps): include missing @grpc/grpc-js dependency

---

.jsdoc.js
.readme-partials.yml
README.md
samples/README.md
synth.metadata

link to other Pub/Sub resources in header based on feedback from product team.

docs: improve header linking to other external docs

---

src/topic.ts

Fixes https://github.com/googleapis/nodejs-pubsub/issues/687

docs(topic): fix createSubscription option documentation

---

samples/system-test/subscriptions.test.js

see: https://github.com/eslint/eslint/issues/11899#issuecomment-516176955

chore: fix linting

---

package.json

see: googleapis/nodejs-speech#243

fix(deps): explicit update to google-auth-library with various fixes

---

src/default-options.ts
src/lease-manager.ts
src/message-stream.ts
src/publisher/index.ts
src/pull-retry.ts
src/subscriber.ts
test/lease-manager.ts
test/message-stream.ts
test/publisher/index.ts
test/pull-retry.ts

Implements the missed parts of https://github.com/googleapis/nodejs-pubsub/issues/858 (batch settings and retry code changes).

feat: update defaults for batch settings also, and update which result codes will cause a retry

---

test/publisher/message-queues.ts

fix: use any to unblock typescript compilation bug
