src/index.js
src/subscription.js
src/topic.js

docs: Subscription names are required.

---

package.json
src/subscription.js
test/subscription.js

The acknowledge and modifyAckDeadline API requests seem to have a size
limitation: If you send to many ackIds with one request you may get the
following error:
```
Request payload size exceeds the limit: 524288 bytes.
```
In order to prevent this error, make sure to always send those requests
in chunks that are small enough.
Fixes #62.

Send acknowledge/modifyAckDeadline requests in chunks

---

package.json
src/index.js
test/index.js

Pull gRPC from google-gax

---

src/connection-pool.js
test/connection-pool.js

Fixes #23 
The chain:
- ConnectionPool#createConnection() - "I need the GAPIC client"
- PubSub#getClient() - "I need the project ID"
- GoogleAutoAuth#getProjectId() - "I'll store the project ID on pubsubInstance.projectID"
The execution path then goes back to where it started, inside ConnectionPool#createConnection. The problem is that function wasn't getting a live representation of the projectId, it was using a local cache it made when it was instantiated.

fix: ConnectionPool#createConnection: Use correct location of projectId.

---

src/topic.js

ackDeadline will not affect new subscription
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/create

DOC: Fix ackDeadline configuration for subscription

---

package.json

We don't need a timeout. It's causing problems in the build, and in the worst case scenario where we forget to call `done()`, the build will timeout and destroy itself.
Reference: https://circleci.com/workflow-run/703f2528-bc45-487d-b246-332d52d76584

Remove timeout from unit tests.

---

src/publisher.js
test/publisher.js

lower default publisher maxMillseconds value

---

package-lock.json
package.json
samples/package-lock.json
src/connection-pool.js
src/subscription.js
src/v1/subscriber_client_config.json
system-test/pubsub.js
test/connection-pool.js
test/subscription.js

Depends on google-gax release including https://github.com/googleapis/gax-nodejs/pull/197
Fixes #13 
Fixes #50 
Fixes #66 
Closes #94 
The overall goal of this PR is to refactor flow control.
Initially we thought a memory leak might be present (#13) however after investigating we found that writing to the server is significantly slower than reading from it and we needed to update our inventory after the write completes. Currently we update our inventory right before we write to the server, assuming that operation will resolve quickly, which sometimes it does not. This caused an increase in memory usage because we were flooding our write buffer with requests faster than they could be processed.
We also discovered a GAX issue, which would report a false positive on the completion time of …

refactor: flow control updates

---

src/subscription.js

docs(subscription): add mention of auto-leasing

---

package-lock.json
package.json
protos/google/pubsub/v1/pubsub.proto
samples/package-lock.json
smoke-test/publisher_smoke_test.js
src/index.js
src/v1/doc/google/iam/v1/doc_iam_policy.js
src/v1/doc/google/iam/v1/doc_policy.js
src/v1/doc/google/protobuf/doc_duration.js
src/v1/doc/google/protobuf/doc_empty.js
src/v1/doc/google/protobuf/doc_field_mask.js
src/v1/doc/google/protobuf/doc_timestamp.js
src/v1/doc/google/pubsub/v1/doc_pubsub.js
src/v1/index.js
src/v1/publisher_client.js
src/v1/subscriber_client.js
synth.py
test/gapic-v1.js
test/index.js

Update google-gax and add Synth.py

---

src/topic.js

Fixes #179 
Added a missing return statement. This change should propagate to the auto-generated docs page.

Fixes 179: Adds missing return statement in docs

---

.circleci/config.yml
samples/package.json
src/publisher.js
synth.py
test/publisher.js

Fixes #177 
If the attributes object has non-string values, publishing fails.
This change adds extra checks to ensure all values are string typed.
Additionally, this precondition is documented.
Testing Done:

Fixes 177: Prevents publishing attributes that have non-string values

---

samples/subscriptions.js
samples/system-test/subscriptions.test.js

The desired output would look something like this (to show users that they can use `modifyAckDeadline` to reset the ack deadline while waiting for the message to get processed):
```
Reset ack deadline for "m4" for 30s.
Reset ack deadline for "m4" for 30s.
Reset ack deadline for "m4" for 30s.
Acknowledged "m4".
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Reset ack deadline for "m1" for 30s.
Acknowledged "m1".
Done.
```

Pub/Sub Synchronous Pull Example

---

samples/subscriptions.js

This new code sample for synchronous pull with lease management aims to keep the Pub/Sub logic and the application logic separate, by 
1). creating the long running process outside in a worker function, and using `setTimeout` to simulate this process of unknown length; 
2). making use of `setInterval` instead of a `for` loop. 
Here is what the stdout would look like:
```
Processing "hello me" for 60.227s...
Processing "hello him" for 95.585s...
Reset ack deadline for "hello me" for 30s.
Reset ack deadline for "hello him" for 30s.
Reset ack deadline for "hello me" for 30s.
Reset ack deadline for "hello him" for 30s.
Reset ack deadline for "hello me" for 30s.
Reset ack deadline for "hello him" for 30s.
Reset ack deadline for "hello me" for 30s.
Reset ack deadline for "hello him" for 30s. …
```

(New) Synchronous Pull with Lease Management 

---

src/publisher.js
test/publisher.js

Fixes #279 and #280.
Regression test added.
Please let me know if you prefer me to split this up in separate PRs.

Fix maxBytes batching sending empty messages

---

src/connection-pool.ts

Fixes #311 partially for src/connection-pool.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for src/connection-pool.ts

---

test/histogram.ts

Fixes #311 partially for test/histogram.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for test/histogram.ts

---

src/iam.ts

Fixes #311 partially for src/iam.ts (it's a good idea to open an issue first for discussion)

refactor(ts): added ts style fix for src/iam.ts

---

CHANGELOG.md

It was reported that when upgrading from v0.19 to v0.20 an error about requiring new was exposed. Adding a note about this change to the changelog

Add migration for v0.20.0 from v0.19.0

---

src/index.ts
src/subscription.ts

This was a new feature added to the API - however since we have a separate set of docs for the manual layer of this library, we would often miss changes to the request configs. We need a way to not have to maintain two separate sets of config objects.

fix(docs): add subscription expiration policy docs

---

src/topic.ts
test/topic.ts

feat(topic): create method for publishing json

---

src/subscriber.ts
src/subscription.ts
test/subscriber.ts
test/subscription.ts

Relates to https://github.com/googleapis/nodejs-pubsub/issues/314#issuecomment-456460023

feat(subscription): auto close sub on non-recoverable errors

---

src/message-queues.ts
src/message-stream.ts
test/message-queues.ts
test/message-stream.ts

refactor: improve subscriber error handling

---

samples/system-test/topics.test.js

fix(sample): factor setTimeout jitter into assertion

---

src/index.ts
test/index.ts

Fixes #288
Fixes #445
---
Looks like not passing the project ID into the gapic clients causes a bunch of future `getProjectId` calls which makes CPU usage spike pretty high
```sh
[Summary]:
ticks  total  nonlib   name
3380   67.2%   71.3%  JavaScript
[Bottom up (heavy) profile]:
ticks parent  name
922   18.3%  LazyCompile: *auth.getProjectId /Users/taco/projects/temp/node_modules/@google-cloud/pubsub/build/src/index.js:599:36
921   99.9%    LazyCompile: *getProjectIdAsync.then.r /Users/taco/projects/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:73:43
921  100.0%      T node::RunMicrotasks(v8::FunctionCallbackInfo<v8::Value> const&)
921  100.0%        LazyCompile: ~_tickCallback internal/process/next_tick.js:41:25
```

fix(auth): pass project id to gax clients

---

smoke-test/publisher_smoke_test.js

If we had charged tests for using lines of stdout, this one would've gone bankrupt soon.
(I use this in gax system tests and hate it when I need to scroll down tons of lines this test prints)

test: make smoke test spam less

---

samples/topics.js

Fixes retry codes in sample code.
These were updated in #419, but it looks like both the previous and the updated values are wrong, gax expects retry codes as numbers. 
The documentation for gax-nodejs also looks flawed (http://googleapis.github.io/gax-nodejs/global.html#RetryOptions), I've opened a PR to update the docs there to.
It takes a bit of time to figure out how to actually set up custom retry for pubsub, it would be a bit easier if the sample codes are updated.

fix(sample): fix retry codes in retry sample code

---

CHANGELOG.md

Fixes #465
Will add to the official release notes after approved.

docs: make mention of message change in changelog

---

src/index.ts
src/publisher.ts
src/snapshot.ts
src/subscription.ts
src/topic.ts
test/snapshot.ts

steps
enable noImplicityAny, for snapshot.ts and publisher.ts file in SRC folder!

refactor(typescript): noImplicityAny for snapshot.ts and publisher.ts

---

src/lease-manager.ts
src/subscriber.ts
system-test/pubsub.ts
test/lease-manager.ts
test/subscriber.ts

fix: ignore messages that come in after close

---

package.json
src/index.ts
src/message-queues.ts
src/message-stream.ts
src/topic.ts
system-test/pubsub.ts

Fixes #313 (it's a good idea to open an issue first for discussion)

refactor(typescript): noImplicityAny for index.ts

---

test/subscription.ts

refactor(typescript): noImplicitAny for subscription test file

---

samples/system-test/topics.test.js

This PR fixes sample test `should publish with specific batch settings` (based on the discussion in #491). I was debugging totally different stuff but realized you're talking about something very interesting and could not resist from debugging this test as well. Good news by the way: sample tests work perfectly with `grpc-js`. Just wanted to let you folks know :)
I added all possible logging to the test (#493 shows my test runs) and found some interesting things that I'd like to share with you folks.
1. `setTimeout` is very accurate. Only once in all my tests it fired 1 ms earlier than needed, and I guess it's more like a time precision problem than the actual early run.
2. The test failure is caused by the sad fact that `publishTime` returned by Pub/Sub is always a _whole second_. Since …

test: fix publishTime issues

---

samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js

Re: https://github.com/googleapis/nodejs-pubsub/pull/494#issuecomment-466521584
Today I learned that passing a `Date` object to `Date.parse` rounds off milliseconds. I'm guessing we did this because the REST API returns an ISO string and it probably was overlooked when converting to grpc.
Additionally I made a small edit to the `exec` function to make debugging Samples a little less painful.

test(samples): correctly handle publishTime value

---

package.json

feat(typescript): ship typescript declaration files

---

src/message-stream.ts
test/message-stream.ts

Relates to https://github.com/grpc/grpc-node/issues/752

fix(messageStream): remove call to destroy grpc stream

---

package.json
src/subscriber.ts
test/subscriber.ts

`publishTime` is returned with microsecond precision, seems like a great use case for precise date!

feat(message): use precise-date for message publish time

---

test/iam.ts

refactor(typescript): noImplicitAny for IAM test file

---

test/histogram.ts
test/message-queues.ts

refactor(typescript):noImplicitAny for Histogram and Message_queues test file

---

src/iam.ts

fix(ts): fix getPolicy promise return signature

---

src/iam.ts
src/index.ts
src/snapshot.ts
src/subscription.ts
src/topic.ts

TypeScript removes any docs it finds above interfaces/overloads/etc. This PR moves any typedefs to the corresponding method and places overloads above method docs.

fix(docs): ensure docs are not removed by typescript

---

package.json
proto/iam.d.ts
src/iam.ts
src/index.ts
src/publisher.ts
src/snapshot.ts
src/subscription.ts
src/topic.ts
system-test/pubsub.ts
test/iam.ts
test/index.ts
test/snapshot.ts
test/subscription.ts
test/topic.ts

refactor(typescript): various fixes/refactors to types

---

test/publisher.ts

refactor(typescript): noImplicitAny for publisher test file

---

system-test/pubsub.ts

towards #313  (it's a good idea to open an issue first for discussion)

refactor(typescript): noImplicitAny for pubsub system test file

---

src/topic.ts
test/index.ts

refactor(typescript):noImplicitAny for index test file

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/pubsub v0.27.0

---

test/message-stream.ts

refactor(typescript): noImplicitAny for message-stream test file

---

package.json
system-test/fixtures/sample/package.json
system-test/fixtures/sample/src/index.ts
system-test/fixtures/sample/tsconfig.json
system-test/install.ts

Relates to https://github.com/googleapis/nodejs-pubsub/issues/526#issuecomment-471020084

test: add missing packages and install test

---

package.json
src/pubsub.ts
test/index.ts

I think the recent upgrade to gax 1.x borked master, I think this should fix it.

refactor: use core grpc

---

src/message-stream.ts
test/message-stream.ts

Relates to https://github.com/googleapis/nodejs-pubsub/issues/468#issuecomment-493661518
The PubSub team would prefer that we do not provide this option.

revert!: remove pullTimeout subscriber option

---

package.json

Relates to https://github.com/grpc/grpc-node/issues/883
Latest version of the gRPC extension results in a slew of TypeScript errors. I believe the culprit is the `@types/protobufjs` package (which is deprecated). I think the best course of action is to just pin it for now.

fix(typescript): pin grpc to previous working version

---

src/subscription.ts
system-test/pubsub.ts
test/subscription.ts

fix(subscription)!: decouple retainAckedMessages from messageRetentionDuration

---

src/subscription.ts

docs(subscription): mention 100 stream limit

---

package.json

Fixes #643 
The extend module used in pubsub package is 3.0.1 which has known vulnerability - Refer https://nvd.nist.gov/vuln/detail/CVE-2018-16492
This vulnerability is fixed in version 3.0.2 of extend module.

deps: upgrade extend dependency to 3.0.2 due to CVE-2018-16492

---

package.json
src/index.ts
src/message-queues.ts
src/message-stream.ts
src/pubsub.ts
src/pull-retry.ts
system-test/pubsub.ts
test/message-queues.ts
test/message-stream.ts
test/pubsub.ts
test/pull-retry.ts
test/subscription.ts
test/topic.ts

fix(deps)!: use grpc-js instead of grpc extension

---

src/subscriber.ts
test/subscriber.ts

revert(message)!: remove nack delay parameter

---

src/subscription.ts

docs(subscription): fix broken links to pubsub methods

---

.jsdoc.js
package.json
src/index.ts
src/pubsub.ts

This fixes *many* problems we had with the jsdoc-baseline template, including not rendering `ClientConfig` properties in line with the constructor.

docs: use jsdoc-fresh as the template

---

src/index.ts
src/message-queues.ts
src/message-stream.ts

This provides us with more detailed debug information so that we can better delve into intermittent issues with `grpc-js`.

feat(debug): capture stack trace in errors rather than message

---

samples/system-test/topics.test.js
samples/topics.js

+ Wraps `await` in an anonymous `async` function. This makes sure that the code enclosed in the region tags can run as copied and pasted. 
+ Publish multiple messages instead of one to better showcase what batch publishing is all about. 
+ Update the test to show that when `maxMessages` is 10, publishing 10 messages should take shorter than the `maxWaitTime`.

docs: update batch publish sample

---

proto/iam.d.ts
protos/google/iam/v1/iam_policy.proto
protos/google/iam/v1/options.proto
protos/google/iam/v1/policy.proto
protos/google/type/expr.proto
samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js
system-test/pubsub.ts

One consequence of #730 is that it will take up to date protos for IAM. Normally, this should not be an issue, but seems there was a slight change in the return value of setting IAM policy (added `condition: null` to the result). In this PR I'm updating the protos, the generated `.d.ts` files for IAM, and system/sample tests.

feat: update IAM protos

---

samples/topics.js

The current settings for RPC timeouts sample don't work. After discussion with @anguillanneuf @kir-titievsky @kamalaboulhosn, we decided to change the settings to the following:
* Initial RPC timeout: 5s (5000 ms)
* Max RPC timeout: 10m (600000 ms)
Will be filing a separate PR to update the defaults in the client library as well.

docs: update publish sample's rpc timeout settings

---

package.json

Folks in #739 might be using an old version of `google-gax`. Let's explicitly bump the dependency then.

chore(deps): update dependency google-gax to ^1.5.2

---

.readme-partials.yml
README.md

Updates documentation documenting how one goes about swapping in the `grpc` dependency, rather than `@grpc/grpc-js`. We've been finding for some workloads, `grpc` can be a more stable choice.
fixes #781 
see #770

fix(docs): add documentation about running C++ gRPC bindings

---

samples/system-test/subscriptions.test.js
samples/system-test/topics.test.js
system-test/pubsub.ts

RE: #826 (not sure it's a fix yet)
Fixes: #821 
This test was failing locally for me:
```
1) pubsub
Snapshot
seeking
should seek to a snapshot:
Uncaught AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 6 ALREADY_EXISTS: Resource already exists in the project (resource=gcloud-tests-snapshot-6dc2ee71-1574603452115).
at subscription.createSnapshot (system-test/pubsub.ts:730:18)
at Immediate.request [as _onImmediate] (src/subscription.ts:464:11)
at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:30:26)
at Http2CallStream.call.on (node_modules/@grpc/grpc-js/build/src/client.js:96:33)
at process.nextTick (node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22)
at process.internalTickCallback (internal/process/next_tick.js:70:11)
```
This throws back to …

test(system): fix snapshot tests

---

package.json
src/pubsub.ts
src/subscription.ts
src/topic.ts

The `is` module was creating TypeScript compilation errors.  Just getting rid of it.

refactor: drop usage of is

---

linkinator.config.json

This is a follow-on to this PR: https://github.com/googleapis/nodejs-pubsub/pull/844
This finishes resolving the chicken and egg problem with the linkinator errors from the README updates.

chore: revert the linkinator change from refactor-samples so that it checks those docs again

---

linkinator.config.json

Removes the temporary linkinator exception required to get this through: https://github.com/googleapis/nodejs-pubsub/pull/856

chore: remove temporary linkinator exception from PR #856

---

.github/workflows/ci.yaml

If successful, this will try to shift some of the burden of precommit checks away from Kokoro, to help speed up the process and save us usage quota.

chore: first pass at github actions for some of the repo's precommit checks

---

src/subscription.ts
system-test/pubsub.ts
test/subscription.ts

This fixes a bug in the seek() method that prevented users from passing a date correctly. This is especially relevant for purging (seek to the future).
May relate: https://github.com/googleapis/nodejs-pubsub/issues/905
Related internally: 150712874

fix: send the ITimestamp protobuf to Pub/Sub for seeking, not JavaScript Date()

---

test/lease-manager.ts

Related to https://github.com/googleapis/nodejs-pubsub/issues/884

tests: lease manager maxExtension test was flaky; remove random number generation and increase the buffer to avoid possible float errors

---

src/topic.ts

The old link wasn't valid anymore, I'm guessing due to an update to the docs site.

docs: update site link for UpdateTopicRequest

---

.github/workflows/ci.yaml
src/publisher/index.ts
src/publisher/message-queues.ts
src/pubsub.ts
src/topic.ts
test/publisher/index.ts
test/pubsub.ts

Fixes: https://github.com/googleapis/nodejs-pubsub/issues/817

feat: add a close() method to PubSub, and a flush() method to Topic/Publisher

---

src/v1/publisher_client.js
synth.py
system-test/pubsub.ts

Fixes: https://github.com/googleapis/nodejs-pubsub/issues/937
The issue is that our TypeScript gapic generator provides a close() method, but the old JavaScript one doesn't seem to. So the close() feature addition was relying on some invalid typings. I've backported that for publisher client, and added a system-test that will hopefully catch future issues.
Going forward, the TypeScript gapic upgrade is definitely the right fix here, but that's also going to bump us up to Node 10+, so I want to fix this existing feature first.

fix: provide missing close() method in the generated gapic client

---

src/v1/subscriber_client.js
synth.py
system-test/pubsub.ts

Apparently the gapic generated SubscriberClient also doesn't have a `close()` method. This adds another synth.py hack and corresponding change in the .js file. Also a new system-test to catch subscribers specifically.
Follow-on fix for https://github.com/googleapis/nodejs-pubsub/issues/937
A proper fix is happening at https://github.com/googleapis/nodejs-pubsub/pull/923 but it will require bumping major versions, so I'm basically backporting this for 1.7.x.

fix: add a close() method to the generated SubscriberClient for 1.x

---

CHANGELOG.md
package.json
samples/package.json

Beep boop!
Manual release on the legacy-8 branch.

chore: release 1.7.2

---

src/iam.ts
src/publisher/index.ts
src/snapshot.ts
src/topic.ts
test/iam.ts
test/publisher/index.ts
test/pubsub.ts
test/snapshot.ts
test/subscription.ts
test/topic.ts

BREAKING CHANGE: This change removes the `PubSub.Promise` property that could be used to override the default Promise implementation in node.js.  In years past, this option made sense as native Promise support on the platform lagged behind.  Today, the promise implementation in node.js is complete and performant.

chore!: drop support for custom promises

---

src/message-queues.ts
src/subscriber.ts
system-test/pubsub.ts
test/message-queues.ts
test/subscriber.ts

Backporting this fix to the legacy-8 branch.

fix(close): ensure in-flight messages are drained (#952)

---

bin/benchwrapper.js
package.json
src/index.ts
src/message-queues.ts
src/message-stream.ts
src/publisher/publish-error.ts
src/pubsub.ts
src/pull-retry.ts
test/message-queues.ts
test/message-stream.ts
test/publisher/publish-error.ts
test/pubsub.ts
test/pull-retry.ts

Getting rid of any direct dependency on gRPC.
~~Also, `grpc` dev dependency looks completely unused, so removing it :)~~
Upd. It's used by `bin/benchwrapper.js`. Changed that to use gRPC exported from `google-gax` as well.

refactor: use grpc from google-gax

---

src/iam.ts
src/pubsub.ts
src/subscription.ts
src/topic.ts

fix(docs): link to correct gaxOptions docs

---

samples/createSubscriptionWithDeadLetterPolicy.js
samples/removeDeadLetterPolicy.js
samples/synchronousPullWithDeliveryAttempts.js
samples/system-test/subscriptions.test.js
samples/updateDeadLetterPolicy.js
samples/updateDeadLetterPolicyExample.js

sample: add samples for dead letter topics
